[shell]
# program = "zellij"
# args = ["-l", "welcome"]
# args = ["attach", "0-default", "--create"]
program = "tmux"
args = ["attach", "-t", "0"]

[window]
startup_mode = "Maximized"
dynamic_title = false
