theme = "kaolin-dark"

[editor]
true-color = true
line-number = "relative"

[editor.cursor-shape]
select = "underline"
insert = "bar"

[editor.soft-wrap]
enable = true

[keys.normal]
A-j = "scroll_down"
A-k = "scroll_up"

C-l = "jump_view_right"
C-h = "jump_view_left"
C-k = "jump_view_up"
C-j = "jump_view_down"

C-r = "redo"

C-S-x = "increment"
A-x = "increment"
